### ISSUE TITLE
solving SPC python version dependency

### ISSUE THREAD

**Issue by Hussein-Mahfouz** [Urban-Analytics-Technology-Platform/acbm#10]
I tried to install geopandas using `poetry add geopandas` but got the following error:

> [BUG] uatk-spc (0.1.0) @ git+https://github.com/alan-turing-institute/uatk-spc.git@55-output-formats-python#subdirectory=python is not satisfied.

I ran some other commands such as `poetry update` and also got an error:

> The current project's Python requirement (>=3.10) is not compatible with some of the required packages Python requirement:
>   - uatk-spc requires Python ^3.10, so it will not be satisfied for Python >=4.0
> 
> Because acbm depends on uatk-spc (0.1.0) @ git+https://github.com/alan-turing-institute/uatk-spc.git@55-output-formats-python#subdirectory=python which requires Python ^3.10, version solving failed.
> 
>   • Check your dependencies Python requirement: The Python requirement can be specified via the `python` or `markers` properties
>     
> For uatk-spc, a possible solution would be to set the `python` property to ">=3.10,<4.0"
>

@sgreenbury should the spc python dependency be changed from "^3.10" to ">=3.10,<4.0", or is this problem related to something else in my setup? Not sure if I should have posted this in https://github.com/alan-turing-institute/uatk-spc/

**Comment by sgreenbury** [comment]
Thanks for raising this and apologies `uatk-spc` caused a problem with the update. Having an upper limit on the python version in `uatk-spc` is unnecessary I think, so I have [removed this](https://github.com/alan-turing-institute/uatk-spc/pull/67/commits/ad1d8267e563348bd9634f5773c64bd98e76bd96), which should fix the issue.

**Comment by Hussein-Mahfouz** [comment]
Great thanks Sam. I managed to update uatk-spc but I'm still unable to install geopandas. I get the following error when running `poetry install geopandas`. The error message below suggests this has to do with an upper limit on python:

![image](https://github.com/Urban-Analytics-Technology-Platform/acbm/assets/45176416/6ef866b7-10d7-4f11-9a55-630155527cc2)

It could also be that I am installing geopandas incorrectly. The [documentation](https://geopandas.org/en/stable/getting_started/install.html#installation) suggests using conda and warns that the C library dependencies can be challenging to install. 

Just documenting for now, but will revisit next week and ping you then if I'm still struggling with it

**Comment by Hussein-Mahfouz** [comment]
changing the python version in this repo's `pyproject.toml `seems to have worked
